#4-date-slider-addition
natlex/City_past_frontend pull request #10
Opened 2020-11-30 14:07 UTC by oyikagawa

Добавил date slider, использовал этот - https://github.com/angular-slider/ngx-slider.
Также добавил тики с промежутком в 10 лет, думаю, так выглядит получше, чем просто пустая линия.

2020-12-01 06:23 UTC, artfulsage requested changes

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/app.module.ts
> +import {NgxSliderModule} from '@angular-slider/ngx-slider';
@oyikagawa пробелы внутри {}. Также проверь в других файлах. И хорошо бы отсортировать по алфавиту импорты.

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/app.module.ts
> +    DateSliderComponent
@oyikagawa добавь запятую в конце. Также пробегись по всем похожим местам. Не буду каждое место отмечать

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.css
> +  width: auto;
@oyikagawa `width: auto;`, мне кажется, не имеет смысл, точно без этого не работает?

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.html
> +  <ngx-slider [(value)]="value" [(highValue)]="highValue" [options]="options" (userChangeEnd)="onDateSliderChange($event)"></ngx-slider>
@oyikagawa лучше, когда каждый атрибут выводится на новой строке. Это правило есть во многих системах форматирования, в том числе в vscode

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
@oyikagawa на текущий момент я бы убрал тесты из проекта. И можно поставить отдельную задачу по изменению конфига проекта, чтобы тесты не создавались автоматически при генерации компонента

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +  styleUrls: ['./date-slider.component.css']
@oyikagawa добавь `changeDetection: ChangeDetectionStrategy.OnPush`. И также можно как-то то ли настроить в конфиге проекта, то ли еще как-то, чтобы это значение выставлялось автоматически при генерации компонента. Можно опять же в виде отдельной задачи, т.к. потребует изучения

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +  constructor() { }
@oyikagawa пустые конструкторы не нужны

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +  ngOnInit(): void {
@oyikagawa пустые обработчики хуков тоже не нужны, удали его и `implements OnInit`

2020-12-01 06:23 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +  onDateSliderChange(event: any): void {
@oyikagawa тип `any` лучше по возможности избегать, но, конечно, не в пользу `Object`. Поищи какой тип на самом деле у `event` и поставь его

2020-12-01 06:23 UTC, artfulsage commented on src/src/index.html
> -
@oyikagawa таких изменений в файлах я лично стараюсь всегда избегать, если они только не находятся рядом с местом, в которое я вношу правки, потому что это не относится к решаемой задаче и отвлекает ревьюера, особенно при массовом появлении. Чтобы они в принципе не появлялись, нужно всем использовать одинаковые правила форматирования кода. Но если уж появились, лучше сделать отдельный коммит с чисткой кода.

2020-12-03 15:32 UTC, oyikagawa commented
@artfulsage вроде бы все пофиксил.
+добавил, чтобы автоматом тесты скипались и ChangeDetectionStrategy.OnPush ставился.

2020-12-04 11:13 UTC, artfulsage requested changes

2020-12-04 11:13 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +    console.log(`Start: ${event.value} End: ${event.highValue}`);
@oyikagawa сделай `emit` этих дат через `EventEmitter` (надо его добавить), и пусть в консоль выводятся значения уже там, где ты подпишешься на него (в `app-root`)

тогда мы как раз будем уверены, что `DateSliderComponent` работает как надо, без его внутренних модификаций для отладки

2020-12-04 11:13 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +    ceil: 2020,
@oyikagawa `ceil` должен определяться динамически на основе текущей даты

2020-12-06 15:19 UTC, oyikagawa commented
@artfulsage добавил EventEmitter и исправил дату.

2020-12-07 15:09 UTC, artfulsage requested changes

2020-12-07 15:09 UTC, artfulsage commented on src/src/app/date-slider/date-slider.component.ts
> +  @Output() onSliderChange = new EventEmitter<ChangeContext>();
@oyikagawa лучше избавиться от зависимости `ChangeContext` и завести свой интерфейс с датами, чтобы передавать его через `EventEmitter`. Тогда в будущем мы с легкостью можем изменить внутреннюю реализацию слайдера на что-то другое.

Интерфейс лучше описать в файле на уровне `/app/date-slider`. Папку `models` я не вижу смысла заводить.

2020-12-07 18:37 UTC, oyikagawa commented on src/src/app/date-slider/date-slider.component.ts
> +  @Output() onSliderChange = new EventEmitter<ChangeContext>();
@artfulsage интерфейс добавил.

2020-12-09 04:35 UTC, artfulsage approved these changes

2020-12-09 04:36 UTC, merged