#23 Add Google maps
natlex/City_past_frontend pull request #27
Opened 2020-12-17 11:54 UTC by natlex-to-me

2020-12-18 22:08 UTC, SashnikovNA commented
@artfulsage посмотри плиз

2020-12-20 06:27 UTC, artfulsage requested changes
@natlex-to-me все очень даже не плохо, по мелочам можно предложить улучшения, но не буду 🙂 только тест для компоненты с картой удали, и пусть карта отображается на всю площадь main-компонента. и отлично сделано с ключом карты 👍

2020-12-20 11:34 UTC, natlex-to-me commented
@artfulsage , поправил.

2020-12-21 15:01 UTC, artfulsage approved these changes

2020-12-21 15:02 UTC, merged