#20 Add dummy marker storage service
natlex/City_past_frontend pull request #36
Opened 2020-12-22 06:20 UTC by natlex-to-me

2020-12-25 17:19 UTC, artfulsage requested changes

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/main/components/google-map/google-map.component.ts
> +  private readonly _url =
@natlex-to-me лучше сделать отдельный сервис по загрузке скрипта и спрятать там url. В него же будет инжектиться и конфиг. Причем, как понимаешь, из кофига нужно убрать опции для начальной визуализации карты. Т.е. завести два инъекшн токена - для сервиса загрузки и для компонента.

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/main/components/google-map/google-map.component.ts
> +        takeUntil(this._alive$)
@natlex-to-me здесь не должно быть такой долгой подписки, чтобы ждать уничтожения компонента. Добавление маркера - короткая асинхронная операция. Ну и она не должна зависеть от того, загрузили мы другие точки или нет. Надо это переделать, и я еще сомневаюсь, что `this._addMarker()` реально добавляет точку на карту

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/app.module.ts
> +      googleMapUrlBase: MapUrlBase,
@natlex-to-me эта ссылка на скрипт, вряд ли, изменится, можно ее ближе к использованию описать

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/app.module.ts
> +      options: MapOptions,
@natlex-to-me опции для компонента лучше инжэктить в модуле, где описан компонент, ведь там они и будут применены, и можно без константы

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/main/components/google-map/google-map.component.html
> +    <ng-container *ngFor="let marker of markers$ | async">
@natlex-to-me лучше сразу подготовить в `ts` массив со значениями, чтобы не пришлось так описывать `position` здесь

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/main/services/marker-storage.service.ts
> +    return of(marker).pipe();
@natlex-to-me а зачем здесь `pipe()`?

2020-12-25 17:19 UTC, artfulsage commented on src/src/app/main/components/google-map/google-map.component.ts
> +    const newMarker = <Marker>{
@natlex-to-me буквально на днях в картах поменялись типы, теперь этот тип называется `google.maps.MapMouseEvent`. Скорее всего, еще стоит обновить пакет

2020-12-26 22:21 UTC, natlex-to-me commented on src/src/app/main/components/google-map/google-map.component.ts
> +    const newMarker = <Marker>{
@artfulsage при обновлении пакета @types/googlemaps@3.43.0 возникает проблема
```posh
 Namespace 'google.maps' has no exported member 'MouseEvent'.
```

Подробности тут https://github.com/DefinitelyTyped/DefinitelyTyped/issues/50253

2020-12-28 07:36 UTC, artfulsage approved these changes, later dismissed

2021-01-04 16:00 UTC, artfulsage approved these changes

2021-01-04 16:00 UTC, merged