#2 Header
natlex/City_past_frontend pull request #38
Opened 2020-12-24 21:04 UTC by alexevnaa

2020-12-25 17:23 UTC, artfulsage requested changes

2020-12-25 17:23 UTC, artfulsage commented on src/src/app/header-panel/header-panel.component.html
> +          <img src="assets/img/User avatar.svg" alt="user">
@alexevnaa пробелы не стоит использовать в именах файлов. Переделай на `_` или `-`

2020-12-26 09:08 UTC, alexevnaa commented on src/src/app/header-panel/header-panel.component.html
> +          <img src="assets/img/User avatar.svg" alt="user">
@artfulsage переименовала.

2020-12-28 07:32 UTC, artfulsage approved these changes

2020-12-28 07:33 UTC, merged