Add about modal window
natlex/City_past_frontend pull request #47
Opened 2021-01-22 09:50 UTC by natlex-to-me

2021-01-22 10:01 UTC, natlex-to-me commented
Есть проблема с "прыгающей" кнопкой закрытия окна, которую я так и не смог победить.

"Прыгание" происходит когда кнопка начинает вылезать за рамки модального окна. Прыжок происходит в двух местах.
1. При открытии окна крестик рисуется сначала в уголке частично, затем полностью.
2. При закрытии окна крестик появляется где-то справа около границы окна.

(1) прыжок, наверное, происходит из-за изменения CSS свойств на модальном окне. Как вариант решения -- отключение анимации `BrowserAnimationsModule` и подключение `NoopAnimationsModule`.

2021-01-24 07:19 UTC, artfulsage requested changes

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/modal/modal/modal.component.html
> +  <h2 mat-mat-dialog-title>{{ title }}</h2>
@natlex-to-me опечатка в `mat-mat-dialog-title` - лишний `mat`

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/shared/shared.module.ts
> +export class SharedModule {}
@natlex-to-me не вижу смысла в этом модуле. он уменьшает прозрачность и может подтягивать ненужные импорты. лучше импортировать все напрямую на месте. к примеру, даже, казалось бы вездесущий `CommonModule`, на самом неделе не всегда нужен. я с таким сталкивался на практике

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/modal/modal/modal.component.ts
> +    console.log(title);
@natlex-to-me забыл убрать `console.log`

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/modal/modal.service.ts
> +@Injectable({ providedIn: ModalModule })
@natlex-to-me мне кажется, лучше провайдить в `root`. почему ты выбрал модуль?

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/modal/modal.module.ts
> +export class ModalModule {}
@natlex-to-me `AboutComponent` не должен объявляться в `ModalModule`, т.к. они из разных подсистем

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/header-panel/header-panel.component.html
> +      <span>{{ SiteSectionTypeNames.about }}</span>
@natlex-to-me думаю, в общем случае текст кнопки может вполне отличаться от заголовка модалки, поэтому не вижу смысла в использовании глобального `SiteSectionTypeNames`. подобная константа с заголовком могла бы быть в подсистеме About, но, думаю, что и это избыточно, проще продублировать надписи

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/modal/modal/modal.component.html
> +  <img src="assets/img/close.svg" />
@natlex-to-me ты не думал использовать `mat-icon` с `close`? возможно, проще было бы со стилями и не нужна была бы картинка

2021-01-24 07:19 UTC, artfulsage commented on src/src/app/modal/modal.service.ts
> +    const config = <MatDialogConfig>{
@natlex-to-me такой конфиг лучше задать через токен `MAT_DIALOG_DEFAULT_OPTIONS`

2021-01-24 12:20 UTC, artfulsage requested changes

2021-01-24 12:20 UTC, artfulsage commented on src/src/app/main/maps.module.ts
>  import { NgModule } from '@angular/core';
@natlex-to-me ненужное изменение файла

2021-01-24 12:20 UTC, artfulsage commented on src/src/styles.css
> +  width: 80vw;
@natlex-to-me может быть должно быть `max-width`? ну а вообще, мне кажется, ширина должна быть по внутреннему контенту модалки

2021-01-24 12:20 UTC, artfulsage commented on src/src/styles.css
> +  --close-icon-color: #796363;
@natlex-to-me цвета лучше в `colors.scss` задать. можно наверно и через такие переменные оставить, я не помню, в чем принципиальные отличия, кроме необходимости импорта файла в случае с `$var`

2021-01-24 12:20 UTC, artfulsage commented on src/src/app/modal/modal/modal.component.ts
> +  createModalComponent<T>(componentType: Type<T>, title?: string) {
@natlex-to-me может красивее передавать параметры без этого метода через `data` как в примере https://material.angular.io/components/dialog/examples?
```ts
this.dialog.open(DialogDataExampleDialog, {
  data: {
    animal: 'panda'
  }
});
```

2021-01-25 07:05 UTC, artfulsage approved these changes

2021-01-25 07:06 UTC, merged