addProject
natlex/City_past_frontend pull request #7
Opened 2020-11-25 12:35 UTC by alexevnaa

2020-11-25 14:51 UTC, artfulsage approved these changes

2020-11-25 14:56 UTC, artfulsage requested changes
Переименуй, пжста, корневую папку в `src`

2020-11-25 17:30 UTC, alexevnaa commented
@artfulsage переименовала папку

2020-11-26 05:16 UTC, artfulsage approved these changes

2020-11-26 05:41 UTC, merged